server_name: "Our Logger"
server_base_url: "http://localhost:1234"
server_live_url: "http://localhost:1234"
server_private_url: "http://192.168.4.23:1234"
server_public_url: "http://192.168.4.23:1234"
server_port: "1234"
server_api_key: "asdf"
server_login_url_prefix: "asdf"
server_url_prefix: "123456"
server_cookie_name: "our-logger-server"
server_cookie_secret: "asdf="
server_cookie_secret_message: "why"
server_allow_origins: ""
admin_username: "asdf"
admin_password: "asdf"
time_zone: "America/New_York"
save_files_path: "/Users/morpheous/WORKSPACE/GO/FireC2Server/SAVE_FILES"
encryption_key: "asdf"
bolt_db_path: "bolt.db"
log_level: "debug"